site_name: CalSci SDK
site_url: https://calsci-io.github.io/calsci_sdk_docs/
theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer

plugins:
  - search

nav:
    - 'index.md'
    - 'SDK_Overview.md'
    - 'Getting_Started.md'
    - 'Core_App_APIs.md'
    - 'UI_Buffer_System.md'
    - 'App_Development_Patterns.md'
    - 'Platform_Services.md'
    - 'API_Reference_and_Recipes.md'
    - 'Contributing.md'